### ISSUE TITLE
Improvement for Open Air Valve YAML

### ISSUE THREAD

**Issue by roderik-maker** [Flamingo-tech/Open-AIR#7]
I think the YAML file for the open air valve could benefit from adding some more checks. I made some additions and added a load of comments to the file. Wasn't sure if I should post here, or on the open-air-valve page, opted for the open-air-valve page but here is a [link to the thread](https://github.com/thomasvnl/esphome-open-air-valve/issues/3#issue-2156998379).

**Comment by peterfortuin** [comment]
@roderik-maker, it seems that your link is not working any more.

**Comment by roderik-maker** [comment]
I'll try find some time tonight to share it again

**Comment by roderik-maker** [comment]
Its been a very bussy week and I can't find the original either anymore. Here is my current config for 1 of my valves, I think is the best version I currently have. I'll try find time on Saturday to clean it up and add some comments and explanations.

```
substitutions:
  device_friendly_name: "Valve-1"
  valve_as_number_id: "valve_capacity"
  my_stepper_id: "my_stepper"
  valve_capacity_lookup_table: id(valve_capacity_lookup_table)

esphome:
  name: open-air-valve-1
  friendly_name: ${device_friendly_name}
  name_add_mac_suffix: False
  
  on_boot:
    - priority: 700
      then:
      - stepper.set_acceleration:
          id: my_stepper
          acceleration: inf
      - stepper.set_deceleration:
          id: my_stepper
          deceleration: inf
      - stepper.report_position:
          id: my_stepper
          position: 0
      - stepper.set_target:
          id: my_stepper
          target: !lambda 'return id(valve_capacity_lookup_table)[10];'
      - wait_until:
          condition:
            lambda:
              return id(my_stepper).current_position == id(my_stepper).target_position;
      - stepper.set_speed:
          id: my_stepper
          speed: 150 steps/s
      - if:
          condition:
            binary_sensor.is_off: valve_homing_switch
          then:
          - while:
              condition:
                binary_sensor.is_off: valve_homing_switch
              then:
                - stepper.report_position:
                    id: my_stepper
                    position: 0
                - stepper.set_target:
                    id: my_stepper
                    target: -1
                - wait_until:
                    condition:
                      lambda:
                        return id(my_stepper).current_position <= id(my_stepper).target_position;
      - stepper.report_position:
          id: my_stepper
          position: 0
      - stepper.set_target:
          id: my_stepper
          target: 0
      - stepper.set_speed:
          id: my_stepper
          speed: 350 steps/s

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# This is optional and can be commented out to disable the Web Server
web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxx"

ota:
  password: "xxxxxxxxxxxxxxxxx"
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: "192.168.178.88"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Open-Air-${device_friendly_name}"
    password: "xxxxxxxxxxxxx"

captive_portal:

globals:
  - id: valve_capacity_lookup_table
    type: std::vector<int>
    restore_value: no
    initial_value: '{0,47,66,82,94,106,116,125,134,142,150,158,165,172,178,185,191,197,203,209,215,220,225,231,236,241,246,251,256,261,265,270,275,279,284,288,292,297,301,305,309,314,318,322,326,330,334,338,342,346,350,353,357,361,365,368,372,376,380,383,387,391,394,398,401,405,409,412,416,419,423,426,430,433,437,440,443,447,450,454,457,461,464,467,471,474,478,481,484,488,491,494,498,501,504,508,511,514,518,521,525}'

number:
  - platform: template
    name: "Valve Capacity %"
    id: valve_capacity
    optimistic: true
    restore_value: no
    initial_value: 0
    min_value: 0
    max_value: 100
    step: 10
    mode: slider
    on_value:
      then:
        - stepper.set_target:
            id: my_stepper
            target: !lambda |-
              if (x <= 0) { 
                return 0; 
              } else if(x >= 100) {
                return 525;
              } else if (x > 0 && x < 100) {
                int steps = id(valve_capacity_lookup_table)[x];
                return steps;
              } else {
                return 0;
              }

status_led:
  pin:
    number: GPIO33

uart:
#UART For Sensor 1
-  id: uart_sensor_1
   rx_pin: GPIO25
   tx_pin: GPIO26
   baud_rate: 9600

i2c:
#I2C For Sensor 1
- id: i2c_sensor_1
  sda: GPIO16
  scl: GPIO4
  scan: false
  frequency: 400kHz
  
cover:
  - platform: template
    name: "Valve"
    id: valve
    lambda: |-
      if (id(my_stepper).current_position <= 0) {
        return COVER_CLOSED;
      } else if (id(my_stepper).current_position > 0 && id(my_stepper).current_position <= 100) {
        return COVER_OPEN;
      } else {
        return {};
      }
    open_action:
      - number.set:
          id: valve_capacity
          value: 100
      - stepper.set_target:
          id: my_stepper
          target: 525
    close_action:
      - number.set:
          id: valve_capacity
          value: 0
      - stepper.set_target:
          id: my_stepper
          target: 0

stepper:
  - platform: uln2003
    id: my_stepper
    # pin_a: GPIO12
    # pin_b: GPIO13
    # pin_c: GPIO14
    # pin_d: GPIO15
    pin_a: GPIO15  # Swap pin_a and pin_d
    pin_b: GPIO14  # Swap pin_b and pin_c
    pin_c: GPIO13
    pin_d: GPIO12    
    max_speed: 350 steps/s
    acceleration: inf
    deceleration: inf
    sleep_when_done: true

switch:
  - platform: restart
    name: "Reboot valve controller to recalibrate"

binary_sensor:
  - platform: gpio
    id: valve_homing_switch
    pin: GPIO35
    name: "Valve Closed Switch"
    on_press: 
      then:
      - delay: 0.7s
      - if:
          condition:
            - lambda: |-
                return (id(valve).position == COVER_CLOSED);
            - binary_sensor.is_off: valve_homing_switch
          then:
            - script.execute: recalibrate_valve_to_zero

sensor:
  - platform: scd4x
    co2:
      name: "${device_friendly_name} Co2 Sensor"
    temperature:
      name: "${device_friendly_name} Temperature Sensor"
    humidity:
      name: "${device_friendly_name} Humidity Sensor"

script:
  - id: recalibrate_valve_to_zero
    then:
      - stepper.report_position:
          id: my_stepper
          position: 0
      - stepper.set_target:
          id: my_stepper
          target: !lambda 'return id(valve_capacity_lookup_table)[30];'
      - wait_until:
          condition:
            lambda:
              return id(my_stepper).current_position == id(my_stepper).target_position;
      - if:
          condition:
            binary_sensor.is_off: valve_homing_switch
          then:
          - while:
              condition:
                binary_sensor.is_off: valve_homing_switch
              then:
                - stepper.report_position:
                    id: my_stepper
                    position: 0
                - stepper.set_target:
                    id: my_stepper
                    target: -1
                - wait_until:
                    condition:
                      lambda:
                        return id(my_stepper).current_position <= id(my_stepper).target_position;

```
The problem is, if it is really stuck, it'll stay stuck. I still need to add a loop counter that throws an error after x-step attempts and then blocks the stepper motor from moving to prevent damage.
